Fixed CS0414 in Rendezvous.cs:18
Never used variable 'scrollPosition'.

Seemingly, 'scrollPosition' was intended to refer to the eponymous
private parameter of FlightEngineer.settings and was locally defined
to avoid a compilation error. This fix makes the parameter public to
restore the intended behaviour.